[package]
name = "api"
version = "0.1.0"
authors = ["steckel <steckel@inscriptive.com>"]

[dependencies]
iron = "0.5.*"
router = "0.5.*"
env_logger = "0.4.0"

[dependencies.logger]
git = "https://github.com/iron/logger.git"
